# Generated by Django 4.2.4 on 2023-08-22 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_blogcategory_id_alter_blogpageauthor_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcategory",
            name="slug",
            field=models.SlugField(
                allow_unicode=True,
                help_text="A slug to identify posts by this category",
                max_length=255,
                verbose_name="slug",
            ),
        ),
    ]
