# Generated by Django 4.2.4 on 2023-08-23 05:04

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_alter_blogcategory_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpage",
            name="categories",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, related_name="BlogPage_Category", to="blog.blogcategory"
            ),
        ),
    ]
