# Generated by Django 4.2.4 on 2023-08-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_blogpage_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="update_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Post date and time"
            ),
        ),
    ]
